In [1]:
%pip install pandas numpy matplotlib --quiet

Note: you may need to restart the kernel to use updated packages.

In [2]:
# Import necessary libraries
import sqlite3
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%config InlineBackend.figure_format = 'svg'

print("Libraries imported successfully!")

# Connect to the SQLite database
conn = sqlite3.connect("inventory.db")

# Create a cursor object to interact with the database
cursor = conn.cursor()

# Function to run a SQL query and return the results as a DataFrame
def run_query_to_df(cursor, query):
    cursor.execute(query)
    rows = cursor.fetchall()
    
    # Get column names from cursor
    columns = []
    for col in cursor.description:
        columns.append(col[0])

    # Convert to DataFrame
    df = pd.DataFrame(rows, columns = columns)

    return df

Libraries imported successfully!

In [4]:
query = """
SELECT * FROM customers
"""

# Call the function to run the query and display results
result = run_query_to_df(cursor, query)
result

          id      segment         city state      country        market
0          1     Consumer  Brownsville    TX      EE. UU.  Pacific Asia
1          2     Consumer    Littleton    CO      EE. UU.        Europe
2          3     Consumer       Caguas    PR  Puerto Rico         LATAM
3          4     Consumer   San Marcos    CA      EE. UU.        Africa
4          5  Home Office       Caguas    PR  Puerto Rico        Africa
...      ...          ...          ...   ...          ...           ...
20647  20753     Consumer       Caguas    PR  Puerto Rico  Pacific Asia
20648  20754     Consumer   Plainfield    IL      EE. UU.  Pacific Asia
20649  20755     Consumer       Caguas    PR  Puerto Rico  Pacific Asia
20650  20756    Corporate       Berwyn    IL      EE. UU.  Pacific Asia
20651  20757    Corporate        Miami    FL      EE. UU.  Pacific Asia

[20652 rows x 6 columns]

In [50]:
query = """
SELECT quantity, days_scheduled, days_actual, (days_actual/days_scheduled) AS late_risk_rate FROM orders AS o

JOIN customers as c
ON o.customer_id = c.id

JOIN shipping as s
ON o.id = s.order_id

ORDER BY quantity DESC, late_delivery_risk

LIMIT 10
"""

# Call the function to run the query and display results
result = run_query_to_df(cursor, query)
result

   quantity  days_scheduled  days_actual  late_risk_rate
0        23               4            4             1.0
1        22               4            3             0.0
2        22               4            6             1.0
3        22               1            2             2.0
4        22               4            5             1.0
5        21               4            2             0.0
6        21               4            4             1.0
7        21               4            2             0.0
8        21               0            0             NaN
9        21               1            2             2.0