In [1]:
%pip install pandas numpy matplotlib --quiet

Note: you may need to restart the kernel to use updated packages.

In [69]:
# Import necessary libraries
import sqlite3
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%config InlineBackend.figure_format = 'svg'

print("Libraries imported successfully!")

# Connect to the SQLite database
conn = sqlite3.connect("inventory.db")

# Create a cursor object to interact with the database
cursor = conn.cursor()

# Function to run a SQL query and return the results as a DataFrame
def run_query_to_df(cursor, query):
    cursor.execute(query)
    rows = cursor.fetchall()
    
    # Get column names from cursor
    columns = []
    for col in cursor.description:
        columns.append(col[0])

    # Convert to DataFrame
    df = pd.DataFrame(rows, columns = columns)

    return df

Libraries imported successfully!

In [68]:
query = """
SELECT quantity, days_scheduled, days_actual, (days_actual/days_scheduled)*100 AS late_risk_rate FROM orders AS o

JOIN customers as c
ON o.customer_id = c.id

JOIN shipping as s
ON o.id = s.order_id


ORDER BY quantity DESC, late_delivery_risk

LIMIT 10
"""

# Call the function to run the query and display results
result = run_query_to_df(cursor, query)
result

   quantity  days_scheduled  days_actual  late_risk_rate
0        23             4.0          4.0           100.0
1        22             4.0          3.0            75.0
2        22             4.0          6.0           150.0
3        22             1.0          2.0           200.0
4        22             4.0          5.0           125.0
5        21             4.0          2.0            50.0
6        21             4.0          4.0           100.0
7        21             4.0          2.0            50.0
8        21             0.0          0.0             NaN
9        21             1.0          2.0           200.0

In [65]:
query = """
SELECT round(AVG(days_actual/days_scheduled)*100,2) AS avg_late_risk_rate FROM orders AS o

JOIN customers as c
ON o.customer_id = c.id

JOIN shipping as s
ON o.id = s.order_id
"""

# Call the function to run the query and display results
result = run_query_to_df(cursor, query)
result

   avg_late_risk_rate
0              136.69